### ISSUE TITLE
The Bot should never exceed the 140 character limit. 

### ISSUE THREAD

**Issue by JordanDworaczyk** [JordanDworaczyk/EthPriceBot#3]
If the price rises then the tweet space will decrease possiblly leading to a bug if the tweet exceeds the 140 character limit. 

# Task List

- [x] Combine the _change_  and _percentage_ line. 
- [x] Restructured line one. 
- [ ] Past testing phase.

**Comment by JordanDworaczyk** [comment]
This issue can be resolved by changing the format of the tweet and by eliminating redundencies. Such as, repeating the word `last` and combining the _change of percentage_ with the _absolute change_ line. 
For instance, 

**Current Tweet Format:** 

> #Eth price last 24hrs:
Last: $52.85
High: $53.44
Low: $42.50
Percentage: 22.96%
Change: $9.87
Volume: $415014.03
$eth #Ethereum #coinbase

_(char count: 137)_

**Possible improvements:**
1. Combining the `Change` line and the `Percentage` line would save 11 chars. 
2. Restructuring line one, `#Eth price last 24hrs:` , to be, `#Eth past 24hrs`, would save 7 chars.

**Suggested Tweet Format:** 

> #Eth past 24hrs
Last: $52.85
High: $53.44
Low: $42.50
Change: 22.96% | $9.87
Volume: $415014.03
$eth #Ethereum #coinbase

_(char count: 120)_

**Conclusion** 
The proposed changes will reduce the character count be a total of 18 chars. This reduction of chars would eliminate the possibility of reaching the 140 character limit. (Unless the price of Etheruem sky rockets).

**Comment by JordanDworaczyk** [comment]
# Task List

- [ ] Combine the _change_  and _percentage_ line. 
- [ ] Restructuring line one. 
- [ ] Test phase.
